from dataclasses import dataclass
from typing import List, Dict

@dataclass
class ContentSpec:
    subject: str
    content_type: str
    assets: List[str]
    topics: List[str]


CONTENT_REGISTRY: Dict[str, ContentSpec] = {
    "python": ContentSpec(
        subject="python",
        content_type="code_output",
        assets=["code", "explanation"],
        topics=[
            "Variable scope (LEGB rule) and closures",
            "Late binding in closures",
            "Mutability vs immutability (lists, tuples, dicts, sets)",
            "Default argument pitfalls (mutable defaults)",
            "List comprehensions vs generator expressions",
            "Iterator protocol and custom iterators",
            "Generator send(), throw(), and close()",
            "Context managers and __enter__/__exit__",
            "Decorators (function and class decorators)",
            "Decorator execution order and preserving metadata (functools.wraps)",
            "Async/await, event loop, and coroutines",
            "asyncio gathering and common race conditions",
            "Global Interpreter Lock (GIL) impact",
            "Multiprocessing vs threading",
            "Truthiness and __bool__/__len__ magic methods",
            "Chained comparisons (a < b < c)",
            "Integer caching and is vs == operator",
            "String interning and identity",
            "Name mangling in classes (__private)",
            "Descriptors and property decorator internals",
            "Metaclasses and __new__ vs __init__",
            "Multiple inheritance and MRO (C3 linearization)",
            "Slots (__slots__) and memory optimization",
            "Function annotations and type hints",
            "Walrus operator (:=) assignment expressions",
            "Exception handling (else/finally, exception groups in 3.11+)",
            "Import system and relative imports",
            "Module __name__ == '__main__' guard",
            "Copy vs deepcopy (shallow copy pitfalls)",
            "Dictionary key hashing and order preservation",
            "Set operations and frozenset",
            "Lambda limitations and scoping",
            "Star expressions (*args, **kwargs unpacking)",
            "Extended unpacking (e.g., *rest, in lists/tuples)",
            "f-strings internals and evaluation",
            "Data model methods (__repr__, __str__, __eq__, __hash__)",
            "Operator overloading",
            "Duck typing and protocols",
            "Monkey patching",
            "Circular references and garbage collection",
            "Yield from delegation in generators",
            "Structural pattern matching (match/case in 3.10+)",
            "Positional-only and keyword-only parameters",
            "Dataclasses internals and field defaults",
            "Python with Regex",
            "Python memory management and reference counting",
        ],
    ),

    "javascript": ContentSpec(
        subject="javascript",
        content_type="code_output",
        assets=["code", "explanation"],
        topics=[
            "Hoisting and temporal dead zone",
            "Closures and lexical scope",
            "this binding rules (call/apply/bind, arrow functions)",
            "Async/await and promises",
            "Event loop, microtasks, and macrotasks",
            "Prototype chain and inheritance",
            "Array/Object mutation and immutability pitfalls",
            "Type coercion and equality (== vs ===)",
            "ES6+ destructuring and spread/rest tricks",
            "Arrow functions vs regular functions",
            "Event delegation and bubbling/capturing",
            "Strict mode differences and gotchas",
            "Promise chaining and error propagation",
            "Modules (ESM vs CommonJS) and import/export",
            "Optional chaining and nullish coalescing",
            "Symbol and well-known symbols",
            "Proxy and Reflect API traps",
            "Iterator and generator functions",
            "BigInt vs Number edge cases",
            "NaN and Infinity behaviors",
            "Floating point precision issues",
            "Object property enumeration (for...in vs Object.keys)",
            "WeakMap/WeakSet vs Map/Set",
            "Private class fields and methods",
            "Top-level await in modules",
            "IIFE patterns and module scope",
            "Array methods that mutate vs return new (sort, splice, push)",
            "Truthy/falsy values and short-circuiting",
            "Function vs constructor vs class differences",
            "Temporal Dead Zone with const/let/class",
            "Event loop starvation and blocking",
            "Async iterator and for await...of",
            "Dynamic import() and code splitting"
        ],
    ),

    "rust": ContentSpec(
        subject="rust",
        content_type="code_output",
        assets=["code", "explanation"],
        topics=[
            "Ownership and borrowing basics",
            "Lifetimes in functions",
            "Traits and generics",
            "Pattern matching tricks",
            "Error handling with Result",
            "Smart pointers (Rc, Arc, RefCell)",
            "Concurrency with threads and channels",
            "Mutable vs immutable references",
            "Move semantics and Copy trait",
            "Enums and variants with data",
            "Closures and capture modes",
            "Iterator adapters (map, filter, fold)",
            "Macro rules and declarative macros",
            "Unsafe code and raw pointers",
            "Module system and visibility (pub, crate)",
            "Async/await with futures",
            "Borrow checker edge cases",
            "String vs &str handling",
            " interior mutability patterns",
            "Trait objects and dynamic dispatch",
            "Lifetimes in structs and impl blocks",
            "Error propagation with ? operator",
            "Generic bounds and where clauses",
            "Thread safety with Send and Sync",
            "Pin and self-referential structs",
            "Custom derive macros",
            "Borrowing in loops and iterators",
            "Panic vs unwind behavior",
            "Const vs static variables",
            "FFI with external crates"
        ]
    ),

    "golang": ContentSpec(
        subject="golang",
        content_type="code_output",
        assets=["code", "explanation"],
        topics=[
            "Slices vs arrays (length, capacity, appending)",
            "Slice headers and underlying array sharing",
            "Nil slices vs empty slices",
            "Map internals (zero values, nil maps, iteration order)",
            "Map race conditions in concurrent access",
            "Goroutines basics and scheduling",
            "Channels (buffered vs unbuffered, closing, ranging)",
            "Nil channels and select behavior",
            "Select statement ordering and default case",
            "Select with timeouts and context cancellation",
            "Context package patterns (WithCancel, WithTimeout, WithDeadline)",
            "Context value propagation and pitfalls",
            "Interfaces (empty interface, method sets, pointer vs value receivers)",
            "Interface satisfaction rules (pointer receivers on value types)",
            "Type assertions and type switches (comma ok idiom)",
            "Defer execution order (LIFO stack)",
            "Defer with named return values modification",
            "Panic and recover mechanics",
            "Error handling (errors.Is, errors.As, custom error wrapping)",
            "Error wrapping with %w and unwrap chain",
            "Struct tags and reflection",
            "Pointer semantics (nil pointers, escaping to heap)",
            "Escape analysis gotchas",
            "String vs []byte conversion and immutability",
            "Rune vs byte iteration over strings",
            "Sync package (Mutex, RWMutex, WaitGroup, Once)",
            "Sync/atomic operations",
            "Race detector common false positives/negatives",
            "Function closures and captured variables",
            "Method values vs method expressions",
            "Embedding structs and field/method promotion",
            "iota in const declarations",
            "Blank identifier (_) usage and side effects",
            "init() function execution order",
            "Go mod and module path gotchas",
            "JSON marshaling/unmarshaling (tags, private fields, pointers)",
            "Time package pitfalls (monotonic clock, time.After)",
            "Reflection (reflect.Value.CanSet, modifiable values)",
            "Unsafe package (Sizeof, Pointer conversions)",
            "Garbage collection triggers and tuning",
            "Stack vs heap allocation decisions",
            "Range loop variable reuse across iterations",
            "Loop variable capture in goroutines"
        ],
    ),

    "sql": ContentSpec(
        subject="sql",
        content_type="query_output",
        assets=["query", "table"],
        topics=[
            "GROUP BY edge cases (non-aggregated columns, NULL grouping)",
            "JOIN behavior with NULLs (INNER vs LEFT, NULL equality)",
            "HAVING vs WHERE clause differences",
            "Window functions (ROW_NUMBER, RANK, DENSE_RANK differences)",
            "Window frames (RANGE vs ROWS, UNBOUNDED vs CURRENT ROW)",
            "Subqueries vs CTEs (performance, recursion, readability)",
            "Correlated subqueries execution order",
            "EXISTS vs IN subquery pitfalls (NULL handling)",
            "UNION vs UNION ALL (duplicates and performance)",
            "NULL handling in aggregates (COUNT(*), COUNT(col), COALESCE)",
            "Three-valued logic (TRUE/FALSE/UNKNOWN with NULL)",
            "ORDER BY with NULLs (NULLS FIRST/LAST dialect differences)",
            "SELECT DISTINCT vs GROUP BY",
            "Implicit type conversion and comparison surprises",
            "String concatenation and NULL (|| vs CONCAT)",
            "Date/time functions and timezone gotchas",
            "INDEX usage in WHERE vs ORDER BY vs GROUP BY",
            "LIKE pattern matching (escaping %, _)",
            "CASE expression (searched vs simple, NULL evaluation)",
            "PIVOT/UNPIVOT operations (dialect-specific)",
            "Recursive CTEs (cycle detection, depth limiting)",
            "LATERAL joins and cross apply",
            "VALUES clause as table source",
            "INSERT...RETURNING vs OUTPUT (dialect differences)",
            "UPSERT behavior (ON CONFLICT, MERGE)",
            "Transaction isolation levels (phantom reads, dirty reads)",
            "Locking hints and deadlocks",
            "EXPLAIN/EXPLAIN ANALYZE output interpretation",
            "Aggregate filter clauses (FILTER WHERE in PostgreSQL)",
            "Array aggregation and unnesting (PostgreSQL)",
            "JSON functions (JSON_VALUE, JSON_QUERY, ISJSON)",
            "FULL OUTER JOIN unexpected results",
            "Self-joins and aliasing pitfalls",
            "Column alias usage in WHERE vs HAVING vs ORDER BY",
            "LIMIT/OFFSET with ties (FETCH FIRST n ROWS WITH TIES)",
            "GREATEST/LEAST with NULLs",
            "Division by zero and NULL results",
            "Boolean type handling (dialect differences)",
            "String vs numeric comparison collation",
            "Truncation in INSERT/UPDATE (silent failures)",
            "Views and updatable views limitations",
            "Materialized views refresh behavior"
        ],
    ),

    "regex": ContentSpec(
        subject="regex",
        content_type="pattern_match",
        assets=["input", "regex"],
        topics=[
            "Greedy vs lazy (reluctant) vs possessive quantifiers",
            "Backtracking pitfalls and catastrophic backtracking",
            "Positive and negative lookahead",
            "Positive and negative lookbehind (fixed vs variable length)",
            "Character classes vs negated character classes",
            r"Shorthand character classes (\d, \w, \s) and locale differences",
            r"Unicode properties (\p{...}) vs POSIX classes",
            r"Anchors (^, $, \A, \Z, \z) and multiline mode",
            r"Word boundaries (\b vs \B) edge cases",
            "Capturing groups vs non-capturing groups (?:...) ",
            "Named capture groups syntax and access",
            "Backreferences inside and outside the pattern",
            "Atomic groups (?>...) and possession",
            "Conditional patterns (?(group)yes|no)",
            "Recursion and balanced constructs (e.g., nested parentheses)",
            "Alternation ordering and priority (|)",
            "Escaping metacharacters in different contexts",
            "Dot (.) behavior in dotall/singleline mode",
            "Case-insensitive matching and Unicode case folding",
            "Inline modifiers (?i), (?-i), (?ismx)",
            "Comments mode (?(x)...) and free-spacing",
            "Group numbering and duplicate group names",
            "Replacement string references ($1, \1, ${name})",
            "Zero-width matches and empty string matching",
            "Overlapping matches (and why most engines don't support)",
            "Sticky flag (y) in JavaScript",
            "Unicode mode (u) and astral plane characters",
            "Regex engine differences (PCRE vs JavaScript vs Python re)",
            "Lookbehind limitations in JavaScript",
            "Infinite quantifiers on empty strings",
            "Trimming with regex edge cases",
            "Password validation pattern tricks",
            "Email validation myth (why simple regex fails)",
            "HTML tag stripping dangers",
            "Split with capturing groups behavior"
        ],
    ),

    "system_design": ContentSpec(
        subject="system_design",
        content_type="scenario",
        assets=["diagram", "text"],
        topics=[
            "Rate limiting algorithms (token bucket, leaky bucket, fixed/sliding window)",
            "Caching strategies (Cache-Aside, Write-Through, Write-Back, Read-Through)",
            "Cache eviction policies (LRU, LFU, TTL, ARC)",
            "Cache consistency (strong vs eventual, invalidation vs refresh)",
            "Cache stampede/thundering herd prevention",
            "Queue backpressure and flow control",
            "Message queue partitioning and ordering guarantees",
            "Database sharding strategies (range, hash, directory-based)",
            "Database replication (leader-follower, multi-leader, leaderless)",
            "Consistency models (strong, eventual, causal, sequential)",
            "CAP theorem trade-offs and real-world implications",
            "Eventual consistency and conflict resolution (CRDTs, last-write-wins)",
            "Load balancer algorithms (round-robin, least connections, consistent hashing)",
            "Consistent hashing and virtual nodes",
            "Circuit breaker pattern",
            "Retry strategies (exponential backoff, jitter)",
            "Idempotency in APIs and message processing",
            "Distributed transactions (2PC, Saga pattern)",
            "Leader election (Raft, Paxos, Bully algorithm)",
            "Clock synchronization and logical clocks (Lamport, vector clocks)",
            "Bloom filters and probabilistic data structures",
            "Gossip protocol and failure detection",
            "Heartbeats vs deadlines in distributed systems",
            "Service discovery (DNS, Consul, ZooKeeper)",
            "API gateway responsibilities and patterns",
            "Backend-for-Frontend (BFF) pattern",
            "Database indexing trade-offs (B-tree vs LSM)",
            "Write amplification in log-structured storage",
            "Read-heavy vs write-heavy workload optimization",
            "Hot partitioning and hotspot mitigation",
            "Data partitioning by tenant vs by feature",
            "CQRS and event sourcing",
            "Materialized views vs live joins",
            "Distributed locking (Redis, ZooKeeper, etcd)",
            "Lease-based vs heartbeat-based locks",
            "Time-to-live (TTL) in distributed caches",
            "Sidecar vs service mesh pattern",
            "Observability: metrics, logging, distributed tracing",
            "Canary deployments vs blue-green",
            "Feature flags and dark launches",
            "Geo-partitioning and multi-region replication",
            "Disaster recovery (RTO vs RPO)",
            "Cold vs hot standby databases",
            "Handling partial failures and network partitions",
            "Bulkhead pattern and thread pool isolation",
            "Graceful degradation and fallback strategies"
        ],
    ),

    "linux": ContentSpec(
        subject="linux",
        content_type="command_output",
        assets=["terminal"],
        topics=[
            "wc vs awk word/line/count differences",
            "awk field separators (FS, OFS) and default behavior",
            "sed in-place editing (-i) pitfalls and backups",
            "sed address ranges and line selection tricks",
            "Pipe behavior (stdout vs stderr, pipefail)",
            "Exit codes and last command ($?) vs pipeline (${PIPESTATUS[@]})",
            "set -o pipefail effects",
            "Subshells created by pipes vs process substitution",
            "Command grouping {} vs () subshell differences",
            "Redirect order matters (2>&1 vs >&2 vs 2>/dev/null)",
            "Here documents (<<EOF) and here strings (<<<)",
            "Process substitution (<(cmd) vs >(cmd))",
            "Command substitution $() vs backticks behavior",
            "Globbing vs regex (*, ?, [ ], ** in bash)",
            "Brace expansion {a,b,c} vs globbing",
            "find -exec {} + vs {} \\; efficiency",
            "xargs behavior with quotes and empty input",
            "read command pitfalls (IFS, -r, trailing spaces)",
            "trap signals and EXIT/DEBUG/ERR",
            "jobs, fg, bg, and disown behavior",
            "nohup vs & vs screen/tmux differences",
            "tee command overwriting vs appending",
            "cut vs awk field extraction differences",
            "sort -u vs uniq requirements",
            "comm vs diff vs join usage",
            "grep -F vs -P vs -E (fixed, perl, extended)",
            "grep recursive (-r vs -R) and symlink following",
            "alias vs function precedence and expansion",
            "export vs declare -x vs env",
            "env -i and clean environment execution",
            "ulimit and resource limit surprises",
            "umask and default file permissions",
            "/dev/null vs /dev/zero vs /dev/random",
            "dd command block size and conv options",
            "tar extraction overwriting behavior",
            "ln -s vs -f vs -n symlink races",
            "chmod recursive vs X permission tricks",
            "chown --reference and preservation",
            "stat vs ls output differences",
            "du -h vs -d vs --apparent-size",
            "df vs du discrepancies (reserved blocks, mounts)",
            "ps aux vs ps -ef output formats",
            "kill -9 vs -15 vs -0",
            "nice vs renice vs ionice",
            "timeout command and signal forwarding",
            "watch command interval and differences",
            "bash arithmetic $(( )) vs let vs expr",
            "test [ ] vs [[ ]] conditional differences",
            "Bash string manipulation ${var#}, ${var%}, ${var//}",
            "what does ls command do?",
            "what does grep command do?",
            "what does find command do?",
            "what does awk command do?",
        ],
    ),

    "docker_k8s": ContentSpec(
        subject="docker_k8s",
        content_type="qa",
        assets=["question", "explanation"],
        topics=[
            "OOMKilled reasons and memory limits vs requests",
            "Docker image layers (caching, deduplication, layer ordering pitfalls)",
            "Multi-stage builds and final image contents",
            "Dockerfile instruction order impact on cache invalidation",
            "Pod restart policies (Always, OnFailure, Never)",
            "Pod restart vs container restart (init containers, sidecars)",
            "ConfigMaps vs Secrets (mounting, volume differences, immutability)",
            "Secret encoding (base64 quirks, not encryption)",
            "Resource requests vs limits (CPU throttling, memory OOM)",
            "Pod eviction and node pressure (memory, disk, PID)",
            "Liveness vs readiness vs startup probes",
            "Probe failure thresholds and timing gotchas",
            "Init containers execution order and main container delay",
            "Sidecar container patterns and termination order",
            "Volume types (emptyDir, hostPath, persistentVolumeClaim)",
            "emptyDir medium: Memory vs default behavior",
            "PodDisruptionBudget and voluntary disruptions",
            "Taints and tolerations matching rules",
            "Node affinity vs nodeSelector",
            "Pod anti-affinity and topology spread constraints",
            "Service types (ClusterIP, NodePort, LoadBalancer, ExternalName)",
            "Headless services and DNS resolution",
            "Endpoint slices vs legacy endpoints",
            "Ingress vs IngressController differences",
            "Ingress path matching (prefix, exact, regex)",
            "kubectl apply vs create vs replace behavior",
            "Server-side apply and field management conflicts",
            "Kubectl patch types (strategic, merge, json)",
            "RollingUpdate strategy (maxUnavailable, maxSurge)",
            "Pod lifecycle hooks (PostStart, PreStop)",
            "Graceful termination and terminationMessagePolicy",
            "Downward API volume (labels, annotations, resource limits)",
            "Projected volumes (ConfigMap + Secret + DownwardAPI + ServiceAccountToken)",
            "ServiceAccount token mounting and expiration",
            "RBAC role vs clusterRole binding scope",
            "NetworkPolicy ingress/egress rules and default deny",
            "CNI plugin differences (Calico, Flannel, Cilium)",
            "Pod securityContext vs container securityContext",
            "runAsUser, fsGroup, supplementalGroups behavior",
            "HostPID, hostNetwork, hostPort dangers",
            "DaemonSet vs Deployment rollout differences",
            "StatefulSet ordering guarantees and volumeClaimTemplates",
            "HorizontalPodAutoscaler (CPU vs custom metrics)",
            "VerticalPodAutoscaler recommendations",
            "Job vs CronJob backoffLimit and completions",
            "Container image pull policy (Always, IfNotPresent, Never)",
            "Image tag :latest pitfalls",
            "Docker build --no-cache vs cache-from",
            "Multi-arch images and manifest lists",
            "Container runtime differences (containerd vs CRI-O vs Docker)",
            "Kubelet eviction thresholds and signals",
            "What does kubectl get pods do?"
            "What does kubectl describe do?"
            "What does OOMKilled mean?"
            "What does readiness probe do?"
            "What does ConfigMap do?"
            "What is a DaemonSet?"
        ],
    ),

    "mind_benders": ContentSpec(
        subject="mind_benders",
        content_type="puzzle",
        assets=["puzzle", "explanation"],
        topics=[
            # Fun Number Games
            "Find the missing number",
            "Number chain patterns",
            "Quick number sequences",
            "Digit spot patterns",
            "Magic number tricks",
            "Number guessing games",
            "Add and subtract puzzles",
            
            # Basic Math Fun
            "Simple addition riddles",
            "Quick subtraction games",
            "Easy multiplication tricks",
            "Division brain teasers",
            "Fill in the math symbol",
            "Balance the equation",
            "Math crossword puzzles",
            "Number pyramid games",
            "Missing operator puzzles",
            
            # Pattern Games
            "What's the pattern? (numbers)",
            "Color sequence puzzles",
            "Shape pattern games",
            "Growing pattern riddles",
            "Repeating pattern spots",
            "Pattern prediction games",
            "Complete the grid pattern",
            "Row and column patterns",
            "Number grid puzzles",
            
            # Brain Teaser Logic
            "Who said what? (riddles)",
            "Age guess puzzles",
            "Family tree teasers",
            "Quick logic questions",
            "Trick questions (the fun kind)",
            "Lateral thinking brain teasers",
            
            # Time & Day Puzzles
            "Clock and time riddles",
            "Calendar day puzzles",
            "What day is it? puzzles",
            "Time logic games",
            
            # Visual Fun
            "Spot the pattern (shapes)",
            "Emoji math games",
            "Symbol equations",
            "Picture riddles",
            "Shape spot-the-difference",
            "Match the pair games",
            "Spot what's different",
            "Complete the shape sequence",
            "Rotating pattern puzzles",
            
            # Word Play
            "Guess the word from clues",
            "Letter order puzzles",
            "Word scramble logic",
            "Name that month/day riddle",
            "Hidden words puzzle",
            "Word pattern games",
            
            # Direction & Position
            "Left, right, up, down? (compass games)",
            "Where is it? (position puzzles)",
            "Who sits where? (seating games)",
            "Find your way (path puzzles)",
            
            # True or False Logic
            "Is the statement true?",
            "Which one doesn't fit?",
            "Spot the odd one out",
            "Does this follow the rule?",
            
            # Comparison Games
            "Compare and find (bigger, smaller, heavier)",
            "Match the pairs",
            "Is this similar to that?",
            "Find what's alike",
            
            # Mini Mysteries
            "Who did what? (deduction)",
            "Solve the puzzle clue by clue",
            "Mystery box riddles",
            "Detective brain teasers",
            
            # Pattern Recognition
            "What comes next?",
            "Complete the sequence",
            "Find the hidden pattern",
            "Predict the next move",
            "Mirror pattern games",
            "Symmetry spot puzzles",
            
            # Simple Scenario Puzzles
            "What would you do? (quick decisions)",
            "Is this possible?",
            "Can you make this work?",
            "Problem solving quick games",
        ],
    ),

    "psychology": ContentSpec(
        subject="psychology",
        content_type="wisdom_card",
        assets=["statement", "explanation", "example", "application"],
        topics=[
            # Cognitive Biases (12 topics)
            "Confirmation bias in daily decisions",
            "Dunning-Kruger effect and expertise",
            "Anchoring effect in negotiations",
            "Availability heuristic and fear",
            "Sunk cost fallacy in relationships",
            "Halo effect in first impressions",
            "Fundamental attribution error",
            "Hindsight bias and regret",
            "Recency bias in memory",
            "Framing effect in choices",
            "Loss aversion in decision making",
            "Bandwagon effect and conformity",
            
            # Social Psychology (10 topics)
            "Bystander effect in emergencies",
            "Social proof and influence",
            "Groupthink in organizations",
            "Conformity and peer pressure",
            "Obedience to authority figures",
            "In-group bias and tribalism",
            "Self-serving bias in success",
            "Cognitive dissonance resolution",
            "Reciprocity principle in relationships",
            "Mirror neurons and empathy",
            
            # Behavioral Economics (6 topics)
            "Choice overload and paralysis",
            "Default option power",
            "Mental accounting tricks",
            "Temporal discounting and patience",
            "Endowment effect and ownership",
            "Decoy effect in pricing",
            
            # Mental Health & Well-being (10 topics)
            "Stress response mechanisms",
            "Anxiety spiral patterns",
            "Depression and rumination",
            "Burnout warning signs",
            "Emotional regulation techniques",
            "Growth mindset vs fixed mindset",
            "Self-compassion benefits",
            "Gratitude practice effects",
            "Resilience building strategies",
            "Mindfulness and present moment awareness",
            
            # Decision Making (5 topics)
            "Analysis paralysis causes",
            "Intuition vs rational thinking",
            "Decision fatigue impact",
            "Regret minimization framework",
            "Satisficing vs maximizing",
            
            # Habit Formation & Change (8 topics)
            "Habit loop: cue, routine, reward",
            "Implementation intentions power",
            "Tiny habits strategy",
            "Breaking bad habits effectively",
            "Identity-based habit formation",
            "Environment design for behavior change",
            "Temptation bundling technique",
            "Streaks and consistency motivation",
            
            # Relationships & Communication (8 topics)
            "Active listening techniques",
            "Nonviolent communication framework",
            "Attachment styles in relationships",
            "Stonewalling and the four horsemen",
            "Emotional validation impact",
            "Conflict resolution strategies",
            "Assertiveness vs aggression",
            "Love languages and appreciation",
            
            # Memory & Learning (7 topics)
            "Spacing effect for retention",
            "Active recall vs passive reading",
            "Elaborative encoding strategy",
            "Memory palace technique",
            "Interleaving for skill building",
            "Testing effect on learning",
            "Sleep and memory consolidation",
            
            # Emotions & Emotional Intelligence (7 topics)
            "Emotional granularity benefits",
            "Affect labeling to reduce intensity",
            "Reappraisal vs suppression",
            "Emotional contagion awareness",
            "Window of tolerance concept",
            "Primary vs secondary emotions",
            "Emotional intelligence components",
            
            # Motivation & Productivity (8 topics)
            "Intrinsic vs extrinsic motivation",
            "Self-determination theory (autonomy, mastery, purpose)",
            "Progress principle and small wins",
            "Zeigarnik effect (unfinished tasks)",
            "Parkinson's law and deadlines",
            "Flow state conditions",
            "Procrastination psychology",
            "Implementation intentions for goals",
            
            # Self-Awareness & Personal Growth (6 topics)
            "Johari window model",
            "Imposter syndrome patterns",
            "Self-handicapping behavior",
            "Personal values clarification",
            "Narrative identity formation",
            "Meta-cognition and self-reflection",
            
            # Positive Psychology (7 topics)
            "Optimism and explanatory styles",
            "Character strengths identification",
            "Savoring positive experiences",
            "Post-traumatic growth",
            "Meaning and purpose finding",
            "Social connections and happiness",
            "Hedonic vs eudaimonic well-being",
        ]
    ),

    "finance": ContentSpec(
                subject="finance",
                content_type="finance_card",
                assets=["insight", "explanation", "example", "action"],
                topics=[
                    # Investing Basics (12 topics)
                    "Index funds vs active funds",
                    "Dollar-cost averaging strategy",
                    "Asset allocation by age",
                    "Diversification principles",
                    "Risk tolerance assessment",
                    "Compound interest power",
                    "Time in market vs timing market",
                    "ETFs vs mutual funds",
                    "Dividend investing basics",
                    "Growth vs value investing",
                    "International diversification",
                    "Rebalancing portfolio strategy",
                    
                    # Retirement Planning (8 topics)
                    "401(k) employer match maximization",
                    "Roth vs Traditional IRA",
                    "Retirement withdrawal strategies",
                    "Social security optimization",
                    "Healthcare costs in retirement",
                    "Retirement number calculation",
                    "Early retirement considerations (FIRE)",
                    "Required minimum distributions (RMDs)",
                    
                    # Personal Finance Fundamentals (10 topics)
                    "Emergency fund sizing (3-6 months)",
                    "Budgeting frameworks (50/30/20 rule)",
                    "Pay yourself first principle",
                    "Automated savings systems",
                    "Lifestyle inflation awareness",
                    "Net worth tracking importance",
                    "Cash flow management basics",
                    "Financial goal setting SMART method",
                    "Sinking funds for irregular expenses",
                    "Financial independence milestones",
                    
                    # Debt Management (7 topics)
                    "Debt avalanche vs snowball method",
                    "Good debt vs bad debt",
                    "Credit card debt strategies",
                    "Student loan repayment options",
                    "Mortgage refinancing decisions",
                    "Debt consolidation pros and cons",
                    "Zero-based budgeting for debt payoff",
                    
                    # Credit & Banking (6 topics)
                    "Credit score factors and optimization",
                    "Credit utilization ratio impact",
                    "Building credit from scratch",
                    "High-yield savings accounts",
                    "Bank account fees to avoid",
                    "Credit card rewards optimization",
                    
                    # Taxes & Optimization (8 topics)
                    "Tax-advantaged accounts (HSA, FSA)",
                    "Capital gains vs ordinary income",
                    "Tax-loss harvesting strategy",
                    "Marginal vs effective tax rate",
                    "Standard vs itemized deductions",
                    "Tax brackets and planning",
                    "Charitable giving tax benefits",
                    "Freelancer tax considerations",
                    
                    # Risk Management & Insurance (7 topics)
                    "Term vs whole life insurance",
                    "Health insurance deductibles and premiums",
                    "Disability insurance importance",
                    "Umbrella insurance coverage",
                    "Renter's vs homeowner's insurance",
                    "Auto insurance liability limits",
                    "Life insurance needs calculation",
                    
                    # Real Estate & Housing (7 topics)
                    "Rent vs buy decision framework",
                    "Home affordability calculation (28/36 rule)",
                    "Mortgage types and terms",
                    "Down payment strategies",
                    "Real estate investment basics (REITs)",
                    "Property tax considerations",
                    "Home equity lines of credit (HELOC)",
                    
                    # Market Understanding (8 topics)
                    "Bull vs bear markets",
                    "Market cycles and volatility",
                    "Recession indicators and preparation",
                    "Inflation impact on purchasing power",
                    "Interest rate effects on investments",
                    "Market corrections vs crashes",
                    "Economic indicators basics",
                    "Stock market indexes explained",
                    
                    # Behavioral Finance (6 topics)
                    "Loss aversion in investing",
                    "Anchoring bias in financial decisions",
                    "Herd mentality in markets",
                    "Recency bias and past performance",
                    "Emotional investing pitfalls",
                    "Analysis paralysis in choosing investments",
                    
                    # Income & Career (7 topics)
                    "Salary negotiation strategies",
                    "Side hustle economics",
                    "Human capital as an asset",
                    "Career switching financial planning",
                    "Income diversification benefits",
                    "Professional development ROI",
                    "Freelancing vs full-time trade-offs",
                    
                    # Advanced Topics (6 topics)
                    "Alternative investments overview",
                    "Cryptocurrency basics and risks",
                    "Angel investing and startup equity",
                    "Options trading fundamentals",
                    "Real estate crowdfunding",
                    "Peer-to-peer lending risks",
                    
                    # Financial Tools & Systems (5 topics)
                    "Robo-advisors vs DIY investing",
                    "Budgeting apps and automation",
                    "Financial tracking spreadsheets",
                    "Investment fee comparison",
                    "Fintech tools for saving and investing",
                    
                    # Family & Life Events (6 topics)
                    "Newborn financial planning (529 plans)",
                    "Marriage and money conversations",
                    "Divorce financial implications",
                    "Aging parents financial support",
                    "Inheritance and estate basics",
                    "Financial education for kids",
                ],
            ),
}
